// flow-typed signature: 6178e786cf4b53200ae26e42dc43b180
// flow-typed version: <<STUB>>/createjs-easeljs_v^0.8.2/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'createjs-easeljs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'createjs-easeljs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'createjs-easeljs/lib/easeljs-0.8.2.combined' {
  declare module.exports: any;
}

declare module 'createjs-easeljs/lib/easeljs-0.8.2.min' {
  declare module.exports: any;
}

declare module 'createjs-easeljs/lib/easeljs-NEXT.combined' {
  declare module.exports: any;
}

declare module 'createjs-easeljs/lib/easeljs-NEXT.min' {
  declare module.exports: any;
}

declare module 'createjs-easeljs/lib/webgl-0.8.2.combined' {
  declare module.exports: any;
}

declare module 'createjs-easeljs/lib/webgl-0.8.2.min' {
  declare module.exports: any;
}

declare module 'createjs-easeljs/lib/webgl-NEXT.combined' {
  declare module.exports: any;
}

declare module 'createjs-easeljs/lib/webgl-NEXT.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'createjs-easeljs/lib/easeljs-0.8.2.combined.js' {
  declare module.exports: $Exports<'createjs-easeljs/lib/easeljs-0.8.2.combined'>;
}
declare module 'createjs-easeljs/lib/easeljs-0.8.2.min.js' {
  declare module.exports: $Exports<'createjs-easeljs/lib/easeljs-0.8.2.min'>;
}
declare module 'createjs-easeljs/lib/easeljs-NEXT.combined.js' {
  declare module.exports: $Exports<'createjs-easeljs/lib/easeljs-NEXT.combined'>;
}
declare module 'createjs-easeljs/lib/easeljs-NEXT.min.js' {
  declare module.exports: $Exports<'createjs-easeljs/lib/easeljs-NEXT.min'>;
}
declare module 'createjs-easeljs/lib/webgl-0.8.2.combined.js' {
  declare module.exports: $Exports<'createjs-easeljs/lib/webgl-0.8.2.combined'>;
}
declare module 'createjs-easeljs/lib/webgl-0.8.2.min.js' {
  declare module.exports: $Exports<'createjs-easeljs/lib/webgl-0.8.2.min'>;
}
declare module 'createjs-easeljs/lib/webgl-NEXT.combined.js' {
  declare module.exports: $Exports<'createjs-easeljs/lib/webgl-NEXT.combined'>;
}
declare module 'createjs-easeljs/lib/webgl-NEXT.min.js' {
  declare module.exports: $Exports<'createjs-easeljs/lib/webgl-NEXT.min'>;
}
