// flow-typed signature: f6665bca8faba8dbb4f4562ebaef2421
// flow-typed version: <<STUB>>/eslint-cli_v^1.1.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-cli/bin/eslint' {
  declare module.exports: any;
}

declare module 'eslint-cli/lib/get-bin-eslint-js' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-cli/bin/eslint.js' {
  declare module.exports: $Exports<'eslint-cli/bin/eslint'>;
}
declare module 'eslint-cli/lib/get-bin-eslint-js.js' {
  declare module.exports: $Exports<'eslint-cli/lib/get-bin-eslint-js'>;
}
