"use strict";

import React from "react";
import { Table } from "semantic-ui-react";

export class structureTable {
    constructor() {

    }

    getContents() {
        return (
            <Table definition>
                <Table.Header>
                    <Table.Row>
                        <Table.HeaderCell />
                        <Table.HeaderCell>N-glycan</Table.HeaderCell>
                        <Table.HeaderCell>O-glycan</Table.HeaderCell>
                        <Table.HeaderCell>Glycosphingolipids</Table.HeaderCell>
                        <Table.HeaderCell>GAGs</Table.HeaderCell>
                        <Table.HeaderCell>Motifs</Table.HeaderCell>
                    </Table.Row>
                </Table.Header>

                <Table.Body>
                    <Table.Row>
                        <Table.Cell></Table.Cell>
                        <Table.Cell>N-glycan_core</Table.Cell>
                        <Table.Cell>O-glycan_core_1</Table.Cell>
                        <Table.Cell>GSL_core_arthro_type</Table.Cell>
                        <Table.Cell>Hyaluronic_Acid</Table.Cell>
                        <Table.Cell>3'sulfo_Lewis_X</Table.Cell>
                    </Table.Row>
                    <Table.Row>
                        <Table.Cell></Table.Cell>
                        <Table.Cell>N-glycan_fucosylated_core</Table.Cell>
                        <Table.Cell>O-glycan_core_2</Table.Cell>
                        <Table.Cell>GSL_core_gala_type</Table.Cell>
                        <Table.Cell>Chondroitin_4_sulfate</Table.Cell>
                        <Table.Cell>Blood_Group_A_Antigen</Table.Cell>
                    </Table.Row>
                    <Table.Row>
                        <Table.Cell></Table.Cell>
                        <Table.Cell>N-glycan_bisecting_core</Table.Cell>
                        <Table.Cell>O-glycan_core_3</Table.Cell>
                        <Table.Cell>GSL_core_ganglio_type</Table.Cell>
                        <Table.Cell>Chondroitin_6_sulfate</Table.Cell>
                        <Table.Cell>Blood_Group_B_Antigen</Table.Cell>
                    </Table.Row>
                    <Table.Row>
                        <Table.Cell></Table.Cell>
                        <Table.Cell>N-glycan_bisecting_fucosylated_core</Table.Cell>
                        <Table.Cell>O-glycan_core_4</Table.Cell>
                        <Table.Cell>GSL_core_globo_type</Table.Cell>
                        <Table.Cell>Chondroitin_2,6_sulfate</Table.Cell>
                        <Table.Cell>Blood_Group_H_Antigen</Table.Cell>
                    </Table.Row>
                    <Table.Row>
                        <Table.Cell></Table.Cell>
                        <Table.Cell>high-mannose</Table.Cell>
                        <Table.Cell>O-glycan_core_5</Table.Cell>
                        <Table.Cell>GSL_core_isoglobo_type</Table.Cell>
                        <Table.Cell>Chondroitin_4,6_sulfate</Table.Cell>
                        <Table.Cell>Cad_Antigen</Table.Cell>
                    </Table.Row>
                    <Table.Row>
                        <Table.Cell></Table.Cell>
                        <Table.Cell>hybrid</Table.Cell>
                        <Table.Cell>O-glycan_core_6</Table.Cell>
                        <Table.Cell>GSL_core_lact_type</Table.Cell>
                        <Table.Cell>Dematan_sulfate</Table.Cell>
                        <Table.Cell>GD1a</Table.Cell>
                    </Table.Row>
                    <Table.Row>
                        <Table.Cell></Table.Cell>
                        <Table.Cell>complex</Table.Cell>
                        <Table.Cell>O-glycan_core_7</Table.Cell>
                        <Table.Cell>GSL_core_mollu_type</Table.Cell>
                        <Table.Cell>Karatan_sulfate</Table.Cell>
                        <Table.Cell>GD1b</Table.Cell>
                    </Table.Row>
                    <Table.Row>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell>O-glycan_core_8</Table.Cell>
                        <Table.Cell>GSL_core_muco_type</Table.Cell>
                        <Table.Cell>Heparin</Table.Cell>
                        <Table.Cell>GD2</Table.Cell>
                    </Table.Row>
                    <Table.Row>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell>GSL_core_neolacto_type</Table.Cell>
                        <Table.Cell>Heparansan_sulfate</Table.Cell>
                        <Table.Cell>GD3</Table.Cell>
                    </Table.Row>
                    <Table.Row>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell>GM1a</Table.Cell>
                    </Table.Row>
                    <Table.Row>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell>GM1b</Table.Cell>
                    </Table.Row>
                    <Table.Row>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell>GM2</Table.Cell>
                    </Table.Row>
                    <Table.Row>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell>GM3</Table.Cell>
                    </Table.Row>
                    <Table.Row>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell>LacDiNAc</Table.Cell>
                    </Table.Row>
                    <Table.Row>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell>Lactosamin</Table.Cell>
                    </Table.Row>
                    <Table.Row>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell>Lewis_A</Table.Cell>
                    </Table.Row>
                    <Table.Row>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell>Lewis_B</Table.Cell>
                    </Table.Row>
                    <Table.Row>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell>Lewis_C</Table.Cell>
                    </Table.Row>
                    <Table.Row>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell>Lewis_D</Table.Cell>
                    </Table.Row>
                    <Table.Row>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell>Lewis_X</Table.Cell>
                    </Table.Row>
                    <Table.Row>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell>Lewis_Y</Table.Cell>
                    </Table.Row>
                    <Table.Row>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell>P_Antigen</Table.Cell>
                    </Table.Row>
                    <Table.Row>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell>Pk_Antigen</Table.Cell>
                    </Table.Row>
                    <Table.Row>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell>Poly_Lactosamine</Table.Cell>
                    </Table.Row>
                    <Table.Row>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell>Sialy_Lewis_A</Table.Cell>
                    </Table.Row>
                    <Table.Row>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell></Table.Cell>
                        <Table.Cell>Sialy_Lewis_X</Table.Cell>
                    </Table.Row>
                </Table.Body>
            </Table>
        );
    }
}